CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    surname    VARCHAR(50)  NOT NULL,
    name       VARCHAR(50)  NOT NULL,
    patronymic VARCHAR(50)  NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    phone      VARCHAR(12)  NOT NULL UNIQUE,
    country    VARCHAR(50)  NOT NULL,
    city       VARCHAR(50)  NOT NULL,
    address    VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL
    )